import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/navbar/NavBar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal finance app",
  description: "Generated by Pablo Losada",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} h-dvh antialiased grid lg:grid-cols-[auto_1fr] grid-cols-1 pb-12 lg:pb-0`}
      >
        {/* <SideBar /> */}
        <NavBar />
        <div className="relative overflow-y-scroll">{children}</div>
      </body>
    </html>
  );
}
