import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal finance app",
  description: "Generated by Pablo Losada",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} h-dvh antialiased`}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
